# Generated by Django 5.1.2 on 2024-10-24 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('due_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('cp', 'Completed'), ('ip', 'In Progress'), ('fl', 'Failed')], max_length=2)),
                ('slug', models.SlugField(unique=True, unique_for_date='due_date')),
            ],
        ),
    ]
